---
name: release

'on': push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cycjimmy/semantic-release-action@v2
        with:
          branch: ci/github
          extra_plugins: |
            @semantic-release/changelog@3
            @semantic-release/exec@3
            @semantic-release/git@7
          semantic_version: 15.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
